---
title: "Çalışma 1"
---

Bu çalışmada iki görevimiz var.

## (a)  

İlk olarak, seçtiğim [Veri bilimi ve Endüstri Mühendisliği Üzerine Sohbetler - Mustafa Baydoğan & Erdi Daşdemir](https://www.youtube.com/watch?v=1Mvkn71dhaA) videosunda anlatılanlardan kısaca bahsedeceğim.

Karar verme ve sorunların çözümü sürecinde, tahmin ve matematiksel modellerde kullanılacak verinin çıkartılıp işlenmesi önemlidir. İşlenmiş verilerden belirlenen öznitelikler öğrenici algoritmaya verilerek tahmin gerçekleştirilebilir. Karar verme süreçlerinde geleneksel öğrenme ve derin öğrenme yöntemleri izlenebilir. Geleneksel öğrenme, problemin anlaşılıp analiz edilmesi (öznitelik çıkarımı) ve veriye dönüştürüldükten sonra bir modele verilmesi şeklinde ilerlerken, derin öğrenmede ham veriden öznitelik çıkarımı ve öğrenme birlikte yapılmaktadır. Yapısal olmayan verilerle çalışırken kullanışlı olsa da fazla parametre olması nedeniyle açıklanabilirliğinin düşük olması, kirli ve eksik veriden meydana gelen tahmin hatalarının sonuca etkisinin geleneksel yönteme göre daha yüksek olması (yönlendirme ve gürbüzlüğün düşük olması) ve fazla veri gereksinimi nedeniyle bazen geleneksel öğrenmeden geride kalabilir.

Buna göre aşağıdaki durumlardan hangisinde karar verme süreci için derin öğrenme kullanımı daha avantajlıdır?

A\) Tahmin sonuçlarının yorumlanması ve açıklanması gerektiğinde

B\) Eldeki veri metin halinde olduğunda

C\) Tahmin yöntemleriyle elde edilmiş veriler kullanılacağında

D\) Eldeki veri az olduğunda

Doğru Cevap B'dir.

Birçok sektörde üretim-tüketim dengesinin sağlanabilmesi ve dolayısıyla maddi, çevresel vb. zararın en aza indirilebilmesi için tahmin doğruluğu büyük önem taşır. Bu nedenle toplanacak veriler, toplama yaklaşımları, kullanılacak optimizasyon ve tahmin modelleri ve yöntemleri de doğru seçilmelidir. Bu açıdan nokta tahmin yerine aralık tahmini yapmak daha güvenlidir.

Çevrimiçi perakendede ciro eniyileme amacıyla kullanılabilecek pekiştirmeli öğrenme (reinforcement learning) yaklaşımları hangileridir?

-   Akıllı deneme yanılma -\> Farklı algoritmaların belirli sürelerde denenerek en iyisinin bulunması

-   Minimum pişmanlık, maksimum ödül -\> İyi ödül almak için önceden öğrenilen bilgilerin kullanılması, keşfetmek ve büyük ödülleri almak içinse yeni şeylerin denenmesi

-   Basit sıralama politikası -\> Önerilen sıralama skorunu, taraflı veriyi engellemek için belirlenmiş bir katsayı ile çarparak dinamik skor elde edilmesi

Makine öğrenmesinin optimizasyonu iyileştirmek için kullanılması, örneğin her gün kullanılan bir optimizasyon modelinin çözüm verilerini kullanarak yeni gün için çözüm elde edilmesi gibi konular da günümüzde sıkça çalışılmaktadır.

## (b)

İkinci kısımda ise, dslabs paketinden polls_us_election_2016 veri setini kullanarak verilen görevleri tamamlayacağım.

```{r}

#| label: soru4

#install.packages("dslabs", repos = "https://cran.rstudio.com/")
#install.packages("dslabs")
library(dslabs)
data(polls_us_election_2016)

#length(polls_us_election_2016$state)
#length(polls_us_election_2016$population)

my_first <- "Esin"
my_birth_year <- 1991

k <- (nchar(my_first) + my_birth_year) %% 15 + 8

head(polls_us_election_2016, k)

sum(is.na(polls_us_election_2016))

#sum(is.na(polls_us_election_2016[1:8]))

#names(polls_us_election_2016[1:8])
#is.na(polls_us_election_2016[1:8])

# colSums - AI, baska yolu var mi?
#colSums(is.na(polls_us_election_2016[1:8]))

sort(colSums(is.na(polls_us_election_2016[1:8])), decreasing = TRUE)

#sort(colSums(is.na(polls_us_election_2016)), decreasing = TRUE)


#class(polls_us_election_2016$rawpoll_mcmullin)
#class(polls_us_election_2016$adjpoll_mcmullin)
#class(polls_us_election_2016$rawpoll_johnson)
#class(polls_us_election_2016$adjpoll_johnson)
#class(polls_us_election_2016$grade)
#class(polls_us_election_2016$samplesize)


#numeric ve integer olan sütunlar, sapply(polls_us_election_2016, class) yazınca her sütunun class ı  

#numeric ve integer sütunları verileriyle birlikte tablo şeklinde geldi

#polls_us_election_2016[sapply(polls_us_election_2016, is.numeric)]

#new_election <- polls_us_election_2016

#new_election[] <- lapply(new_election, function(x) {
  
#  if (is.numeric(x)) {
    
#    ifelse(is.na(x), my_birth_year + k, x)
    
#  } else if (is.character(x)){
  
#    ifelse(is.na(x), paste0(my_first, "_", k), x)
    
#  } else if (is.factor(x)){ 
  
# karaktere çevirerek yapmak      
#    x <- as.character(x)
#    ifelse(is.na(x), paste0(my_first, "_", k), x)
    
# factor olarak yapmak, factor sütunlarda ifelse hata verirmiş o yüzden önce karaktere çevriliyor, ama bunu yapınca 11175 NA çıktı? diğer ifelse leri de aşağıdaki gibi değiştirince düzeldi, ama anlamı nedir?
   
#   new_val <- paste0(my_first, "_", k)
#   levels(x) <- c(levels(x), new_val)
#   x[is.na(x)] <- new_val
    
#  }
#  return(x) 
  
 #  yeni level eklediğimizde neden gerekli? 
#})



new_election <- polls_us_election_2016

new_election[] <- lapply(new_election, function(x) {
  
  if (is.numeric(x)) {
    
    x[is.na(x)] <- my_birth_year + k
    
  } else if (is.character(x)){
  
    x[is.na(x)] <- paste0(my_first, "_", k)
    
  } else if (is.factor(x)){ 
  
   new_val <- paste0(my_first, "_", k)
   levels(x) <- c(levels(x), new_val)
   x[is.na(x)] <- new_val
    
  }
  return(x) 

})

# testleri


#polls_us_election_2016$samplesize[1802]
#new_election$samplesize[1802] 

#polls_us_election_2016$grade[17]
#new_election$grade[17]

#polls_us_election_2016$grade
#new_election$grade

#polls_us_election_2016$rawpoll_mcmullin
#new_election$rawpoll_mcmullin

# na larin indexleri
#which(is.na(polls_us_election_2016$grade))
#which(is.na(polls_us_election_2016$samplesize))

head(new_election, k)

sum(is.na(new_election))

anyNA(new_election)

```

## 
